# Generated by Django 3.1.5 on 2021-01-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20210129_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('classic_cake', 'Classic Cake'), ('custom_cake', 'Custom Cake'), ('pastries', 'Pastries'), ('gingerbread', 'Gingerbread')], default=None, max_length=12),
        ),
    ]
