# Generated by Django 3.1.5 on 2021-02-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20210129_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1500)),
                ('category', models.CharField(blank=True, choices=[('classic_cake', 'Classic Cake'), ('custom_cake', 'Custom Cake'), ('pastries', 'Pastries'), ('gingerbread', 'Gingerbread')], max_length=12, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
